apiVersion: v1
kind: Service
metadata:
  name: serv-auth
  labels:
    app: taskmgmt

spec:
  type: ClusterIP
  selector: 
    pod_identifier: authpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


